deals/urls.py
from django.urls import path

from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.DealListView.as_view(), name='deal_list'),
    path('submit/', views.DealEditView.as_view(), name='deal_submit'),
    path('<int:pk>/', views.DealView.as_view(), name='deal'),
    path('<int:pk>/edit/', views.DealEditView.as_view(), name='deal_edit'),
    path('<int:pk>/vote/<str:action>/', views.VoteDealView.as_view(), name='deal_vote'),
    path('comments/<int:pk>/vote/<str:action>/', views.VoteCommentView.as_view(), name='comment_vote'),
]

rgundeals/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [

    # Temporary redirect to /deals/
    path('', RedirectView.as_view(url='/deals/'), name='home'),

    # App inclusions
    path('deals/', include('deals.urls')),
    path('users/', include('users.urls')),

    # Admin UI
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

admin.site.site_header = 'rGunDeals Administration'

deals/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Category, Deal


class DealForm(forms.ModelForm):
    """
    Create or edit a Deal
    """
    category = TreeNodeChoiceField(queryset=Category.objects.all())

    class Meta:
        model = Deal
        fields = (
            'title', 'url', 'category', 'price', 'qty', 'discount', 'expires',
            'coupon_code', 'description',
        )
        help_texts = {
            'price': 'Base price in USD (do not include tax/shipping)',
            'qty': 'Number of items/rounds; used to calculate unit cost (optional)',
            'expires': 'Date/time at which this deal expires (optional)<br />'
                       'Format: YYYY-MM-DD [hh:mm:ss]'
        }


class ModDealForm(DealForm):
    """
    Extends DealForm with additional fields for moderators
    """

    class Meta(DealForm.Meta):
        fields = (
            'title', 'url', 'category', 'price', 'qty', 'discount', 'expires',
            'coupon_code', 'description', 'vendor', 'locked',
        )


class ConfirmationForm(forms.Form):
    """
    Generic form used to confirm a potentially dangerous action (e.g. deleting
    an object)
    """
    confirmed = forms.BooleanField(widget=forms.HiddenInput)

deals/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from django.views.generic import View

from utils.pagination import EnhancedPaginator
from .filters import DealFilter
from .forms import DealForm, ModDealForm
from .models import Category, Comment, CommentVote, Deal, DealVote, SCORE_DOWN, SCORE_UP


#
# Deals
#

class DealListView(View):
    """
    Display a list of deals
    """
    template_name = 'deals/deal_list.html'

    def get(self, request):

        # Retrieve all deals
        # TODO: Implement pagination
        queryset = Deal.objects.select_related(
            'created_by', 'edited_by', 'category'
        ).annotate(
            comment_count=Count('comments')
        )

        # Filter the queryset by request parameters
        queryset = DealFilter(request.GET, queryset).qs

        # Annotate vote information for the current user
        if request.user.is_authenticated:
            deal_votes = DealVote.objects.filter(
                deal__in=queryset, user=request.user
            )
            votes = {v.deal_id: v.score for v in deal_votes}
            for d in queryset:
                d.vote = votes[d.pk] if d.pk in votes else None

        # Paginate deals list
        paginator = EnhancedPaginator(queryset, request.GET.get('per_page'))
        deals = paginator.get_page(request.GET.get('page', 1))

        # Get list of all categories
        categories = Category.objects.add_related_count(
            queryset=Category.objects.all(),
            rel_model=Deal,
            rel_field='category',
            count_attr='deal_count',
            cumulative=True
        )

        return render(request, self.template_name, {
            'deals': deals,
            'categories': categories,
        })


class DealView(View):
    """
    Display a single deal and its comments
    """
    template_name = 'deals/deal.html'

    def get(self, request, pk):

        deal = get_object_or_404(Deal, pk=pk)
        if request.user.is_authenticated:
            try:
                vote = deal.votes.get(user=request.user)
                deal.vote = vote.score
            except DealVote.DoesNotExist:
                deal.vote = None

        comments = deal.comments.select_related(
            'created_by', 'edited_by'
        )

        return render(request, self.template_name, {
            'deal': deal,
            'comments': comments,
        })


class DealEditView(LoginRequiredMixin, View):
    """
    Submit a new deal or edit an existing one.
    """
    template_name = 'deals/deal_edit.html'

    def get(self, request, pk=None):

        deal = get_object_or_404(Deal, pk=pk) if pk else None

        if request.user.is_staff:
            form = ModDealForm(instance=deal)
        else:
            form = DealForm(instance=deal)

        return render(request, self.template_name, {
            'form': form,
        })

    def post(self, request, pk=None):

        deal = get_object_or_404(Deal, pk=pk) if pk else None

        if request.user.is_staff:
            form = ModDealForm(data=request.POST, instance=deal)
        else:
            form = DealForm(data=request.POST, instance=deal)

        if form.is_valid():

            deal = form.save(commit=False)
            deal.created_by = request.user
            deal.score = 1
            deal.save()

            if pk:
                messages.success(request, 'Updated deal "{}"'.format(deal))
            else:
                messages.success(request, 'Submitted deal "{}"'.format(deal))

            return redirect(deal)

        return render(request, self.template_name, {
            'form': form,
        })


class VoteDealView(LoginRequiredMixin, View):
    """
    Vote on a deal (up, down, or delete)
    """

    def post(self, request, pk, action):

        deal = get_object_or_404(Deal, pk=pk)

        if action not in ['up', 'down', 'delete']:
            return Http404

        if action in ['up', 'down']:

            vote = {
                'up': SCORE_UP,
                'down': SCORE_DOWN,
            }.get(action)

            # Create a new DealVote or update an existing one
            dv, created = DealVote.objects.update_or_create(
                deal=deal,
                user=request.user,
                defaults={'score': vote}
            )

        else:

            # Delete any existing vote on this deal
            DealVote.objects.filter(deal=deal, user=request.user).delete()

        deal = Deal.objects.get(pk=deal.pk)

        return JsonResponse({
            'voted': True if action in ['up', 'down'] else False,
            'upvote': reverse('deals:deal_vote', kwargs={
                'pk': deal.pk,
                'action': 'delete' if action == 'up' else 'up',
            }),
            'downvote': reverse('deals:deal_vote', kwargs={
                'pk': deal.pk,
                'action': 'delete' if action == 'down' else 'down',
            }),
            'score': deal.score,
        })


# TODO: Merge with VoteDealView
class VoteCommentView(LoginRequiredMixin, View):
    """
    Vote on a comment (up, down, or delete)
    """

    def post(self, request, pk, action):

        comment = get_object_or_404(Comment, pk=pk)

        if action not in ['up', 'down', 'delete']:
            return Http404

        if action in ['up', 'down']:

            vote = {
                'up': SCORE_UP,
                'down': SCORE_DOWN,
            }.get(action)

            # Create a new CommentVote or update an existing one
            dv, created = CommentVote.objects.update_or_create(
                comment=comment,
                user=request.user,
                defaults={'score': vote}
            )

        else:

            # Delete any existing vote on this comment
            CommentVote.objects.filter(comment=comment, user=request.user).delete()

        comment = Comment.objects.get(pk=comment.pk)

        return JsonResponse({
            'voted': True if action in ['up', 'down'] else False,
            'upvote': reverse('deals:comment_vote', kwargs={
                'pk': comment.pk,
                'action': 'delete' if action == 'up' else 'up',
            }),
            'downvote': reverse('deals:comment_vote', kwargs={
                'pk': comment.pk,
                'action': 'delete' if action == 'down' else 'down',
            }),
            'score': comment.score,
        })

templates/deals/deal.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block content %}
    <div class="row">
        <div class="col-12 deal" id="deal{{ deal.pk }}">
            {% if request.user == deal.created_by or request.user.is_staff %}
                <div class="pull-right">
                    <a href="{% url 'deals:deal_edit' pk=deal.pk %}" class="btn btn-warning">
                        <i class="fa fa-pencil"></i> Edit
                    </a>
                </div>
            {% endif %}
            {% include 'deals/inc/deal.html' %}
            {% if deal.description %}
                <div class="description">
                    <div class="card">
                        <div class="card-body">
                            {{ deal.description_rendered|safe }}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    <ul class="list-unstyled comments">
        {% if comments %}
            {% recursetree comments %}
                {% include 'deals/inc/comment.html' %}
            {% endrecursetree %}
        {% else %}
            <li class="text-muted">No comments yet</li>
        {% endif %}
    </ul>
{% endblock %}

templates/deals/deal_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <h1>Submit a New Deal</h1>
            <form action="" method="post">
                {% csrf_token %}
                <div class="row mb-3">
                    <div class="col-md-12">
                        {% bootstrap_field form.title %}
                    </div>
                    <div class="col-md-8">
                        {% bootstrap_field form.url %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.category %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.price %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.qty %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.discount %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field form.expires %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field form.coupon_code %}
                    </div>
                    <div class="col-md-12">
                        {% bootstrap_field form.description %}
                    </div>
                </div>
                {% if user.is_staff %}
                    <div class="card bg-light mb-3">
                        <div class="card-header">Mod Tools</div>
                        <div class="card-body row">
                            <div class="col-md-8">
                                {% bootstrap_field form.vendor %}
                            </div>
                            <div class="col-md-4">
                                {% bootstrap_field form.locked %}
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-md-12 text-right">
                        {% if form.instance.pk %}
                            <button type="submit" class="btn btn-primary">
                                Save
                            </button>
                            <a href="{{ form.instance.get_absolute_url }}" class="btn btn-light">Cancel</a>
                        {% else %}
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-plus"></i> Submit Deal
                            </button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/deals/deal_list.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            {% for deal in deals %}
                <div class="row">
                    <div class="col-12 deal mb-2" id="deal{{ deal.pk }}">
                        <div class="index">
                            {{ deals.start_index|add:forloop.counter0 }}
                        </div>
                        {% include 'deals/inc/deal.html' %}
                        <ul class="list-inline text-muted links">
                            {% if deal.description %}
                                <li class="list-inline-item">
                                    <small>
                                        <i class="fa fa-plus-square"></i>
                                        <a href="#" class="toggle-description" data-deal-id="{{ deal.pk }}">description</a>
                                    </small>
                                </li>
                            {% endif %}
                            <li class="list-inline-item">
                                <small>
                                    <i class="fa fa-comment"></i>
                                    <a href="{{ deal.get_absolute_url }}">{{ deal.comment_count }} comments</a>
                                </small>
                            </li>
                            {% if user.is_staff or user == deal.created_by and not deal.locked %}
                                <li class="list-inline-item">
                                    <small>
                                        <i class="fa fa-pencil"></i>
                                        <a href="{% url 'deals:deal_edit' pk=deal.pk %}">edit</a>
                                    </small>
                                </li>
                            {% endif %}
                            {% if user.is_staff %}
                                <li class="list-inline-item">
                                    <small>
                                        <i class="fa fa-trash"></i>
                                        delete
                                    </small>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class="list-inline-item">
                                    <small>
                                        <i class="fa fa-warning"></i>
                                        report
                                    </small>
                                </li>
                            {% endif %}
                        </ul>
                        {% if deal.description %}
                            <div class="description collapse">
                                <div class="card">
                                    <div class="card-body">
                                        {{ deal.description_rendered|safe }}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <div class="col-12 text-center text-muted">
                    No deals found
                </div>
            {% endfor %}
            {% include 'utils/inc/paginator.html' with page=deals %}
        </div>
        <div class="col-md-3">
            {% if request.user.is_authenticated %}
                <a href="{% url 'deals:deal_submit' %}" class="btn btn-block btn-success mb-3">
                    <i class="fa fa-plus"></i>
                    Submit a Deal
                </a>
            {% endif %}
            <div class="card">
                <div class="card-header">
                    <strong>Categories</strong>
                </div>
                <div class="list-group list-group-flush">
                    {% recursetree categories %}
                        <a href="{{ node.get_absolute_url }}" class="list-group-item list-group-item-action{% if request.GET.category == node.slug %} active{% endif %}">
                            {% if node.parent %}<i class="fa fa-angle-right"></i>{% endif %}
                            {{ node }}
                            <span class="badge {% if request.GET.category == node.slug %}badge-light{% else %}badge-secondary{% endif %} pull-right">{{ node.deal_count }}</span>
                        </a>
                        {% if not node.is_leaf_node %}
                            {{ children }}
                        {% endif %}
                    {% endrecursetree %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}