deals/urls.py
from django.urls import path

from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.DealListView.as_view(), name='deal_list'),
    path('submit/', views.DealEditView.as_view(), name='deal_submit'),
    path('<int:pk>/', views.DealView.as_view(), name='deal'),
    path('<int:pk>/edit/', views.DealEditView.as_view(), name='deal_edit'),
    path('<int:pk>/vote/<str:action>/', views.VoteDealView.as_view(), name='deal_vote'),
    path('comments/<int:pk>/vote/<str:action>/', views.VoteCommentView.as_view(), name='comment_vote'),
]

rgundeals/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [

    # Temporary redirect to /deals/
    path('', RedirectView.as_view(url='/deals/'), name='home'),

    # App inclusions
    path('deals/', include('deals.urls')),
    path('users/', include('users.urls')),

    # Admin UI
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

admin.site.site_header = 'rGunDeals Administration'

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('users/<str:username>/', views.UserView.as_view(), name='user'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}rGunDeals{% endblock %}</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">

            <!--navigation -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
                <a class="navbar-brand" href="#">rGunDeals</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'deals:deal_list' %}">Deals <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        {% if request.user.is_authenticated %}
                            Logged in as <a href="{{ request.user.get_absolute_url }}">{{ request.user }}</a> |
                            {% if request.user.is_staff %}
                                <a href="{% url 'admin:index' %}">Admin</a> |
                            {% endif %}
                            <a href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'users:login' %}">Log In</a> |
                            <a href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </span>
                </div>
            </nav>

            <!-- messages -->
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span>&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}

            <!-- content -->
            {% block content %}{% endblock %}

        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="{% static "js/deals.js" %}"></script>
        <script type="text/javascript">
            var crsftoken = '{{ csrf_token }}';
        </script>
    </body>
</html>